Feature: Configuration Quality Gate

diff --git a/.github/workflows/quality.yml b/.github/workflows/quality.yml
--- a/.github/workflows/quality.yml
+++ b/.github/workflows/quality.yml
@@ -51,13 +51,13 @@ jobs:
         run: |
           echo "Waiting for SonarQube analysis to complete..."
           sleep 20
-          result=$(curl -u "$SONAR_TOKEN": "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY&&branch=${{ github.head_ref }}")
+          result=$(curl -u "$SONAR_TOKEN": "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY&&pullRequest=$PR_ID")
           status=$(echo "$result" | jq -r '.projectStatus.status')
 
           echo "SonarQube Quality Gate status: $status"
           if [ "$status" != "OK" ]; then
-            echo "SonarQube Quality Gate: FAILED"
-            exit 1
+              echo "SonarQube Quality Gate failed"
+              exit 1
           else
-            echo "SonarQube Quality Gate: PASSED"
+              echo "SonarQube Quality Gate passed"
           fi
